version: "3.8"
services:
  php_apache:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html/ventasPet  # Mapea el directorio actual al directorio raíz de Apache
    restart: always