import BaseApiService from "./baseApiService";

export class MenuService extends BaseApiService {
    async getAll() {
        return Promise.resolve([
            { name: 'Pacientes', key_: 'pacientes' },
            { name: 'Pacientes | Evolución del paciente', key_: 'pacientes_evolucion_paciente' },
            { name: 'Pacientes | Consultas', key_: 'pacientes_consultas' },
            { name: 'Pacientes | Consultas | IA', key_: 'pacientes_consultas' },
            { name: 'Pacientes | Ordenes Medicas', key_: 'pacientes_notas_ordenes_medicas' },
            { name: 'Pacientes | Recetas', key_: 'pacientes_recetas' },
            { name: 'Pacientes | Incapacidades', key_: 'pacientes_incapacidades' },
            { name: 'Pacientes | Antecedentes', key_: 'pacientes_antecendetes' },
            { name: 'Pacientes | Consentimientos', key_: 'pacientes_consentimientos' },
            { name: 'Pacientes | Presupuestos', key_: 'pacientes_presupuestos' },
            { name: 'Pacientes | Notas Enfermeria', key_: 'pacientes_notas_enfermeria' },
            { name: 'Pacientes | Evoluciones', key_: 'pacientes_evoluciones' },
            { name: 'Pacientes | Remisiones', key_: 'pacientes_remisiones' },
            { name: 'Pacientes | Info Paciente', key_: 'pacientes_info_paciente' },
            { name: 'Pacientes | Info Paciente | Ver Tel y Correo', key_: 'pacientes_info_paciente_datos_sensibles' },
            { name: 'Pacientes | Telemedicina', key_: 'pacientes_telemedicina' },
            { name: 'Citas', key_: 'citas' },
            { name: 'Citas | Admisiones', key_: 'citas_admisiones' },
            { name: 'Citas | Citas', key_: 'citas_citas' },
            { name: 'Citas | Citas de Espera', key_: 'citas_sala_de_espera' },
            { name: 'Facturación', key_: 'facturacion' },
            { name: 'Facturación | Entidades', key_: 'facturacion_entidades' },
            { name: 'Facturación | Notas ', key_: 'facturacion_notas' },
            { name: 'Configuración', key_: 'configuracion' },
            { name: 'Configuración | Configuración Empresa', key_: 'configuracion_empresas' },
            { name: 'Configuración | Configuración Empresa | Comunicaciones', key_: 'configuracion_empresas' },
            { name: 'Configuración | Entidades', key_: 'configuracion_entidades' },
            { name: 'Configuración | Metodos de Pago', key_: 'configuracion_entidades' },
            { name: 'Configuración | Impuestos a Cargo', key_: 'configuracion_impuestos' },
            { name: 'Configuración | Retenciones', key_: 'configuracion_retenciones' },
            { name: 'Configuración | Centros de Costo', key_: 'configuracion_centro_costo' },
            { name: 'Configuración | Usuarios', key_: 'configuracion_usuarios' },
            { name: 'Configuración | Especialidades', key_: 'configuracion_especialidades' },
            { name: 'Configuración | Roles', key_: 'configuracion_roles' },
            { name: 'Configuración | Horarios', key_: 'configuracion_horarios' },
            { name: 'Configuración | Precios', key_: 'configuracion_precios' },
            { name: 'Configuración | Consentimientos', key_: 'configuracion_consentimientos' },
            { name: 'Configuración | Importaciones', key_: 'configuracion_importaciones' },
            { name: 'Reportes', key_: 'reportes' },
            { name: 'Seguridad', key_: 'seguridad' },
            { name: 'Seguridad | Auditoria', key_: 'seguridad_auditoria' },
            { name: 'Inventarios', key_: 'inventarios' },
            { name: 'Inventarios | Paquetes', key_: 'inventarios_paquetes' },
            { name: 'Marketing', key_: 'marketing' },
            { name: 'Marketing |  Plantillas de Mensaje', key_: 'marketing_plantillas_mensajes' },
            { name: 'Marketing |  Encuestas', key_: 'marketing_encuestas' },
            { name: 'Turnos', key_: 'turnos' },
            { name: 'Turnos | Sala de Espera', key_: 'turnos_sala_espera' },
            { name: 'Turnos | Generar Turnos', key_: 'turnos_generar_turnos' },
            { name: 'Farmacia', key_: 'farmacia' },
            { name: 'Farmacia | Caja', key_: 'farmacia_caja' },
            { name: 'Farmacia | Entrega Insumos', key_: 'farmacia_entrega_insumos' },
            { name: 'Farmacia | Entrega Medicamentos', key_: 'farmacia_entrega_medicamentos' },
        ]);
    }
}